import './globals.css'

import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import Providers from './providers'
import { ThemeProviderWrapper } from '@/contexts/themeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviderWrapper>
          <Providers>{children}</Providers>
        </ThemeProviderWrapper>
      </body>
    </html>
  )
}
